services:
  api:
    image: ${DOCKER_REGISTRY-}wireopscompany
    build:
      context: .
      dockerfile: Company.API/Dockerfile
    ports:
      - "8100:8100"
      - "8101:8101"
    depends_on:
      - db
    environment:
      # Connection string for the application
      ConnectionStrings__DefaultConnection: "Host=db;Port=5433;Database=Company;Username=postgres;Password=postgres"

  db:
    image: postgres:13
    container_name: postgres-company
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Company
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/company/data

volumes:
  db_data:

