services:
  api:
    image: ${DOCKER_REGISTRY-}wireopsbusiness
    build:
      context: .
      dockerfile: Business.API/Dockerfile
    ports:
      - "8100:8100"
      - "8101:8101"
    depends_on:
      - db
    environment:
      # Connection string for the application
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=Business;Username=postgres;Password=postgres"

  db:
    image: postgres:13
    container_name: postgres-business
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Business
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/company/data

volumes:
  db_data:

