version: '3.8'

services:
  api:
    image: ${AWS_ECR_URI}/wireops-business-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Business.API/Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      # DB Configuration
      DB__Host: ${DB_Host}
      DB__Name: ${DB_Name}
      # Auth0 Configuration 
      Auth0__Domain: ${AUTH0_DOMAIN}
      Auth0__Audience: ${AUTH0_AUDIENCE}
      Auth0__ManagementAPIAudience: ${AUTH0_MANAGEMENTAPIAUDIENCE}
      Auth0__UIUrl: ${AUTH0_UI_URL}
      # Mailgun Configuration
      Mailgun__Domain: ${MAILGUN_DOMAIN}
    secrets:
      - db_username  # Maps to DB:USERNAME
      - db_password  # Maps to DB:PASSWORD
      - auth0_client_id      # Maps to Auth0:ClientId
      - auth0_client_secret  # Maps to Auth0:ClientSecret
      - mailgun_api_key      # Maps to Mailgun:APIKey

secrets:
  db_username:
    external: true
  db_password:
    external: true
  auth0_client_id:
    external: true
  auth0_client_secret:
    external: true
  mailgun_api_key:
    external: true