# docker-compose.prod.yml (AWS Production)
version: '3.8'

services:
  api:
    image: ${AWS_ECR_URI}/wireopsbusiness:${TAG:-latest}
    build:
      context: .
      dockerfile: Business.API/Dockerfile
    ports:
      - "80:8100"  # ALB will route to port 80
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Host=${RDS_ENDPOINT};Port=5432;Database=Business;Username=${RDS_MASTER_USERNAME};Password=${RDS_MASTER_PASSWORD}"
      Auth0__Domain: ${AUTH0_DOMAIN}
      Auth0__Audience: ${AUTH0_AUDIENCE}
      Auth0__ManagementAPIAudience: ${AUTH0_MGMT_AUDIENCE}
      Routing__UiUrl: ${PROD_UI_URL}
    secrets:
      - auth0_credentials
      - mailgun_credentials
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# No db service - using Amazon RDS
secrets:
  auth0_credentials:
    external: true  # From AWS Secrets Manager
  mailgun_credentials:
    external: true