version: '3.8'

services:
  api:
    image: wireops-business-api-local
    build:
      context: .
      dockerfile: Business.API/Dockerfile
    ports:
      - "8100:8100"
      - "8101:8101"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: "Server=${DB_HOST};Port=5432;Database=${DB_NAME};Username=${DB_USERNAME};Password=${DB_PASSWORD};"
      Auth0__Domain: ${Auth0_Domain}
      Auth0__Audience: ${Auth0_Audience}
      Auth0__ManagementAPIAudience: ${Auth0_ManagementAPIAudience}
      Auth0__ClientId: ${Auth0_ClientId}
      Auth0__ClientSecret: ${Auth0_ClientSecret}
      Auth0__UIUrl: ${Auth0_UIUrl}
      Mailgun__APIKey: ${Mailgun_APIKey}
      Mailgun__Domain: ${Mailgun_Domain}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-business
    environment:
      POSTGRES_USER: ${DB_Username}
      POSTGRES_PASSWORD: ${DB_Password}
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/company/data

volumes:
  db_data: