version: '3.8'

services:
  api:
    image: wireops-businessapi-local
    build:
      context: .
      dockerfile: Business.API/Dockerfile
    ports:
      - "8100:8100"
      - "8101:8101"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=Business;Username=postgres;Password=${DB_PASSWORD}"
      Auth0__Domain: ${AUTH0_DOMAIN}
      Auth0__Audience: ${AUTH0_AUDIENCE}
      Auth0__ManagementAPIAudience: ${AUTH0_MGMT_AUDIENCE}
      Auth0__ClientId: ${AUTH0_CLIENT_ID}
      Auth0__ClientSecret: ${AUTH0_CLIENT_SECRET}
      Routing__UiUrl: ${UI_URL}
      Mailgun__ApiKey: ${MAILGUN_API_KEY}
      Mailgun__Domain: ${MAILGUN_DOMAIN}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-business
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: Business
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/company/data

volumes:
  db_data: